core/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url

from .views import about_page, contact_page, signup, HomeTemplateView, update_profile

urlpatterns = [
    path('finances/', include('finances.urls')),
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^signup/$', signup, name='signup'),

    path('', HomeTemplateView.as_view(), name='home'),
    re_path(r'^about/$', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('update_profile/<int:pk>/', update_profile, name='update_profile'),

]

finances/api/urls.py
from django.urls import include, path
from rest_framework import routers
from finances.api.views import UserViewSet, GroupViewSet
from finances.views import CreateTransactionAPIView


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('transactions/create/', CreateTransactionAPIView.as_view(),
         name='create_transaction_api'),

    # path('transactions/create/<int:pk>/', CreateTransactionAPIView.as_view(),
    #      name='create_transaction_api'),


]

finances/urls.py
from .api import api_urls
from django.urls import include, path
from .views import finances, ProductView, TransactionView

urlpatterns = [
    path('', finances, name='finances'),
    path('product/', ProductView.as_view(), name='product'),
    path('transaction/', TransactionView.as_view(), name='product_transaction'),
    path('api/', include(api_urls)),
]

masha_crm/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url

from .views import about_page, contact_page, signup, HomeTemplateView

urlpatterns = [
    path('finances/', include('finances.urls')),
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^signup/$', signup, name='signup'),

    path('', HomeTemplateView.as_view(), name='home'),
    # path('', home_page, name='home'),
    re_path(r'^about/$', about_page, name='about'),
    path('contact/', contact_page, name='contact'),

]

finances/models.py
from django.contrib.auth.models import Group
from django.utils.translation import gettext_lazy as _
from django.db import models, transaction
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import Sum


class Currency(models.Model):
    class Meta:
        verbose_name = _('Currency')
        verbose_name_plural = _('Currencies')

    name = models.CharField(max_length=255, verbose_name=_('Name'))
    iso_code = models.CharField(max_length=3, verbose_name=_('ISO Code'))

    def __str__(self):
        return "{} ({})".format(self.name, self.iso_code)


class AccountType(models.Model):
    class Meta:
        verbose_name = _('Account type')
        verbose_name_plural = _('Account types')

    name = models.CharField(max_length=255, verbose_name=_('Name'))
    can_attach_to_user = models.BooleanField(
        default=False,
        verbose_name=_('Can attach to user'),
        help_text=_('Set it if this account can be attach to user')
    )
    visible_by = models.ManyToManyField(
        Group,
        verbose_name=_('Visible by'),
        help_text=_('Who sees accounts in outgoing transactions'),
        related_name='visible_accounttypes',
        blank=True
    )
    accessible_by = models.ManyToManyField(
        Group,
        verbose_name=_('Accessible by'),
        help_text=_('Who can access accounts to incoming/outgoing transactions and can see balance'),
        related_name='accessible_accounttypes',
        blank=True
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    class Meta:
        verbose_name = _('Account')
        verbose_name_plural = _('Accounts')

    name = models.CharField(max_length=255, verbose_name=_('Name'))
    type = models.ForeignKey(AccountType, on_delete=models.PROTECT, verbose_name=_('Type'))

    def __str__(self):
        return self.name


class AccountBalance(models.Model):
    class Meta:
        unique_together = (('account', 'currency'),)

    account = models.ForeignKey(Account, on_delete=models.CASCADE, verbose_name=_('Account'), related_name='balances')
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT, verbose_name=_('Currency'))
    balance = models.DecimalField(max_digits=20, decimal_places=2, verbose_name=_('Balance'))

    def __str__(self):
        return "{}: {}{}".format(self.account.name, self.balance, self.currency.iso_code)


class ProductProvider(models.Model):
    class Meta:
        verbose_name = _('Provider')
        verbose_name_plural = _('Providers')

    name = models.CharField(max_length=255, verbose_name=_('Name'))

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    name = models.CharField(max_length=255, verbose_name=_('Name'))
    provider = models.ForeignKey(ProductProvider, on_delete=models.PROTECT, verbose_name=_('Provider'))
    cost = models.DecimalField(max_digits=20, decimal_places=2, verbose_name=_('Сost'))
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT, verbose_name=_('Currency'))

    def __str__(self):
        return "{} (виробник: {}), вартість {}{}".format(self.name, self.provider, self.cost, self.currency.iso_code)


class Transaction(models.Model):
    class Meta:
        verbose_name = _('Transaction')
        verbose_name_plural = _('Transactions')

    STATUSES = (
        ('buy', 'Купівля'),
        ('sale', 'Продаж'),
    )

    sent_from = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    sent_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='sent_transactions')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product')
    value = models.DecimalField(max_digits=20, decimal_places=2)
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT, related_name='currency')
    surcharge = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True,
                                    verbose_name=_('Surcharge'))
    type = models.CharField(max_length=15, choices=STATUSES, default="sale")
    created_at = models.DateTimeField(auto_now_add=True)
    is_refund = models.BooleanField(default=False)
    # account_balance = models.ForeignKey(AccountBalance, on_delete=models.CASCADE, related_name='account_balance')
    # new_balance = models.DecimalField(null=True, blank=True, default=None, max_digits=20, decimal_places=2)


    # def save(self, **kwargs):

        # with transaction.atomic():
        #     if not self.need_to_approve and not self.pk:
        #         self.account_balance_from.balance -= self.value_from
        #         self.account_balance_from.save()
        #         if self.account_balance_to.currency.iso_code == 'UAH':
        #             self.account_balance_to.balance += (self.value_to - self.short_change)
        #         elif self.account_balance_from.currency.iso_code != 'UAH':
        #             self.account_balance_to.balance += self.value_to
        #             if self.short_change:
        #                 self.account_uah_balance.balance -= self.short_change
        #                 self.account_uah_balance.save()
        #             if self.surcharge:
        #                 self.account_uah_balance.balance += self.surcharge
        #                 self.account_uah_balance.save()
        #         else:
        #             self.account_balance_to.balance += self.value_to
        #         self.account_balance_to.save()
        #         self.new_balance_from = self.account_balance_from.balance
        #         self.new_balance_to = self.account_balance_to.balance
        #     self.daily_number_increment()
        #     super().save(**kwargs)

    def __str__(self):
        return "Ініціатор - {}, кому - {}, {} товар - '{}', продано за:{}{}, дохід:{}{} ".format(self.sent_from, self.sent_to, self.type, self.product, self.value,
                                                               self.currency.iso_code, self.surcharge, self.currency.iso_code)

finances/forms.py
from django import forms
from .models import Product, Transaction


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        # fields = ('name', 'provider', 'cost', 'currency',)
        fields = '__all__'

        def __str__(self):
            return self.name


class TransactionForm(forms.ModelForm):
    # rate = forms.DecimalField(max_digits=12, decimal_places=6, label=('вартість'))

    class Meta:
        model = Transaction
        fields = ('sent_to', 'product', 'value', )
        labels = {
            'sent_to': 'Клієнт',
            'product': "Продукт",
            'value': "Вартість продажу",
        }

finances/api/views.py
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from finances.api.serializers import UserSerializer, GroupSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    # queryset = User.objects.all().select_related('profile')
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


# class ProfileForm(viewsets.ModelViewSet):
#     """
#     API endpoint for ProfileForm.
#     """
#     queryset = Profile.objects.all().order_by('-date_joined')


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

finances/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, FormView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Product, Account, Transaction
from .forms import ProductForm, TransactionForm
from django.shortcuts import get_object_or_404
from rest_framework.generics import CreateAPIView, ListAPIView
from .api.serializers import TransactionSerializer
from finances.api.decorators import add_ability_to_create_many_objects


@add_ability_to_create_many_objects
class CreateTransactionAPIView(CreateAPIView):
    queryset = Account.objects.all()
    serializer_class = TransactionSerializer

    def get_serializer_context(self):
        return {'request': self.request}


@login_required
def finances(request):
    return render(request, "finances.html")


class ProductView(LoginRequiredMixin, FormView, ListView):
    paginate_by = 5
    form_class = ProductForm
    template_name = "finances/product_page.html"

    def get_queryset(self):
        queryset = Product.objects.all().order_by('-id')
        return queryset

    def form_valid(self, form):
        self.success_url = self.request.META.get('HTTP_REFERER') or reverse('finances')
        form.save()
        return super().form_valid(form)


class TransactionView(LoginRequiredMixin, FormView, ListView):
    paginate_by = 10
    form_class = TransactionForm
    template_name = "finances/product_transaction.html"

    def get_queryset(self):
        queryset = Transaction.objects.all().order_by('-id')
        return queryset

    def form_valid(self, form):
        self.success_url = self.request.META.get('HTTP_REFERER') or reverse('finances')
        form.save()
        return super().form_valid(form)

templates/finances/product_page.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load bootstrap_pagination %}
{% block content %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add product form</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-body">
            <form action="{% url 'product' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="modal-footer">
                    <button class="btn btn-primary" type="submit">Save</button>
                </div>
            </form>
        </div>
    </div>
  </div>
</div>


<div class="d-flex"> <h3>Список товарів:</h3>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-sm btn-primary ml-auto mb-2" data-toggle="modal" data-target="#exampleModal">Додати продукт</button>
</div>

<div class="table-responsive">
<table class="table">
        <thead class="">
        {#  <thead class="thead-dark">#}
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Назва</th>
            <th scope="col">Виробник</th>
            <th scope="col">Вартість</th>
        </tr>
        </thead>
        <tbody>
    {% for product in object_list %}
            <tr>
                <th scope="row">{{ product.id }}</th>
                <td>{{product.name}}</td>
                <td>{% if product.provider %}{{ product.provider }} {% endif %}{% if not product.provider %} - {% endif %}</td>
                <td>{% if product.cost %}{{ product.cost }} {{ product.currency.iso_code }} {% endif %}{% if not product.cost %} - {% endif %}</td>
            </tr>
        {% endfor %}
  </tbody>
</table>
    </div>

{% if object_list %}
    {% bootstrap_paginate page_obj range=10 show_first_last="true" %}
{% endif %}

{% endblock %}

templates/finances/product_transaction.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load bootstrap_pagination %}
{% block content %}


<div id="main-content">

    <form action="{% url "create_transaction_api"%}" method="post" id="post-form" class="transaction-form">
        <div>
            <div class="col-7">
                {{ form.sent_to|as_crispy_field }}
            </div>
            <div class='table'>
                <fieldset>
                    <div class="form-row col-12">
                        <div class="col-lg-4">
                            {{ form.product|as_crispy_field }}
                        </div>
                        <div class="col-lg-3">
                            {{ form.value|as_crispy_field }}
                        </div>
                    </div>
                </fieldset>
            </div>
            <button class="ml-3 btn btn-primary" type="button" id="add_more">
                <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                Розширити
            </button>
            <button type="submit" class="btn btn-primary transaction-confirm" id="transaction-confirm">Продати</button>
        </div>
    </form>


<h3 class="mt-4">Список транзакцій</h3>
<div class="table-responsive">
<table class="table">
        <thead class="">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Назва продукта</th>
            <th scope="col">Ціна продажу</th>
            <th scope="col">Навар</th>
            <th scope="col">Хто - Кому</th>
            <th scope="col">Час створення</th>
        </tr>
        </thead>
        <tbody>
    {% for product in object_list %}
            <tr>
                <th scope="row">{{ product.id }}</th>
                <td>{{product.product}}</td>
                <td>{{product.value}} {{product.currency.iso_code}}</td>
                <td>{{product.surcharge}} {{product.currency.iso_code}}</td>
                <td> {{ product.sent_from }} > {{ product.sent_to }} </td>
                <td> {{ product.created_at }} </td>
            </tr>
        {% endfor %}
  </tbody>
</table>
    </div>

{% if object_list %}
    {% bootstrap_paginate page_obj range=10 show_first_last="true" %}
{% endif %}

</div>

    <script>
        $('#add_more').click(function () {
            cloneMore('div.table:last');
        });
        function cloneMore(selector) {
            var newElement = $(selector).clone(true);
            newElement.find(':input').each(function () {
                var name = $(this).attr('name') + 1;
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            });
            $(selector).after(newElement);
         }
    </script>

<script>
        window.variables = {
            csrfToken: '{{ csrf_token }}',
        }

        $(document).ready(function () {
            $('.transaction-confirm').on('click', function (e) {
                e.preventDefault();
            let form = $(this).closest('.transaction-form');
            let url = form.attr('action');
            let data = getFormData(form);
            let sent_to_id = data["sent_to"];

            let fieldsets = form.find("fieldset");
            let newData = [];
            let errors = "False";
            fieldsets.each(function () {
                let fieldset = $(this).serializeArray()
                newData.push({"sent_to":sent_to_id , "product": fieldset[0]["value"], "value": fieldset[1]["value"]})
             });

            Object.keys(data).forEach(function (key) {
                if (data[key].length == 0) {
                    errors = "True";
                    $("#id_" + key).css('border', 'solid 1px red');
                } else {
                    $("#id_" + key).css('border', 'solid 1px #ced4da');
                }
            })
                data = {"data": JSON.stringify(newData)}

                if (errors == "False") {
                form.find('input').each(function () { $(this).val("") });
                form.find('select').val("");
                    transactionConfirmRequest(form, url, data)
                }
            });

    const transactionConfirmRequest = (form, url, data) => {
        $.ajax({
            url: url,
            method: 'POST',
            headers: {"X-CSRFToken": variables.csrfToken},
            data,
        }).done(function (data) {
            console.log('done', data)
            $('#main-content').prepend(
                `<div class='alert alert-primary'>Транзакція успішно створена</div>`
            );

        }).fail(function (data) {
            data = data.responseJSON;
            for (let a in data) {
                if (a === 'non_field_errors') {
                    $('.change-validation-message').append(`<p class="excanger-form-validation-backend-checks" style="color: darkred">${data[a][0]}</p>`);
                } else {
                    $(`#id_${a}:not([type='hidden'])`).closest('div').append(`<p class="excanger-form-validation-backend-checks" style="color: darkred">${data[a][0]}</p>`);
                }
             }
        })
    }

            function getFormData($form) {
                let unindexed_array = $form.serializeArray();
                let indexed_array = {};

                $.map(unindexed_array, function (n, i) {
                    indexed_array[n['name']] = n['value'];
                });

                return indexed_array;
            }
        });

</script>

{% endblock %}


{#    <script>#}
{##}
{#        window.variables = {#}
{#            csrfToken: '{{ csrf_token }}',#}
{#        }#}
{##}
{#        $(document).on('submit', '#post-form', function (e) {#}
{#            e.preventDefault();#}
{##}
{#            $.ajax({#}
{#                type: 'POST',#}
{#                url: '{% url "create_transaction_api"%}',#}
{#                headers: {"X-CSRFToken": variables.csrfToken},#}
{#                data: {#}
{#                    client: $('#id_sent_to').val(),#}
{#                    product: $('#id_product').val(),#}
{#                    value: $('#id_value').val(),#}
{#                    action: 'post',#}
{#                },#}
{#                success: function (json) {#}
{#                    document.getElementById("post-form").reset();#}
{#                    console.log("succsess!")#}
{#                },#}
{#                error: function (xhr, errmsg, err) {#}
{#                    console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console#}
{#                }#}
{#            });#}
{#        });#}
{#    </script>#}